service: lambdanamefunc
frameworkVersion: '2'
provider:
  name: aws
  region: eu-central-1
  runtime: nodejs12.x

functions:
  app:
    handler: main.handler
    memorySize: 128
    timeout: 50
    role: arn:aws:iam::734078883937:role/s3-role-lambda
    events:
      - s3:
          bucket: signtests4
          event: s3:ObjectCreated:*
          existing: true