service: Test11
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  app:
    handler: main.handler
    memorySize: 128
    timeout: 50
    role: ${{ secrets.LAMBDA_ROLE }}
    events:
      - s3:
          bucket: ${{ secrets.BUCKETNAME }}
          event: s3:ObjectCreated:*
          existing: true
